// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_8 = "CgkI4Ky9x6cGEAIQCA"; // <GPGSID>
        public const string achievement_9 = "CgkI4Ky9x6cGEAIQCQ"; // <GPGSID>
        public const string achievement_can_master_heaven = "CgkI4Ky9x6cGEAIQCw"; // <GPGSID>
        public const string achievement_can_go_heaven = "CgkI4Ky9x6cGEAIQAA"; // <GPGSID>
        public const string achievement = "CgkI4Ky9x6cGEAIQAQ"; // <GPGSID>
        public const string achievement_2 = "CgkI4Ky9x6cGEAIQAg"; // <GPGSID>
        public const string achievement_3 = "CgkI4Ky9x6cGEAIQAw"; // <GPGSID>
        public const string achievement_6 = "CgkI4Ky9x6cGEAIQBg"; // <GPGSID>
        public const string achievement_7 = "CgkI4Ky9x6cGEAIQBw"; // <GPGSID>
        public const string achievement_4 = "CgkI4Ky9x6cGEAIQBA"; // <GPGSID>
        public const string achievement_5 = "CgkI4Ky9x6cGEAIQBQ"; // <GPGSID>
        public const string achievement_10 = "CgkI4Ky9x6cGEAIQCg"; // <GPGSID>

}

